#!/bin/bash

# Generate build info with current git commit hash
COMMIT_ID=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

cat > lib/build_info.dart << EOF
// GENERATED FILE - DO NOT EDIT
// This file is automatically generated during build
const String buildCommitId = '$COMMIT_ID';
const String buildTimestamp = '$BUILD_TIME';
EOF

echo "Generated build_info.dart with commit: $COMMIT_ID"
